// CHANGELOG.md is generated by conventional-changelog's angular preset (`yarn changelog`): a release
// heading per version, a section heading per commit type, and one bullet per commit. Bullets are not
// uniform — a commit bullet ends in a short-hash link and may carry `, closes [#N](...)` references,
// while a BREAKING CHANGES note has no hash link at all and wraps onto following lines, keeping its
// own paragraphs and sub-lists. Nothing that parses is dropped, because a silently missing entry is
// worse than an oddly formatted one.

// a run of description text, carrying a url when the changelog linked it (issues, users, commits)
export type ChangelogTextSegment = {
  text: string;
  url?: string;
};

export type ChangelogEntry = {
  scope?: string;
  description: ChangelogTextSegment[];
  // absent on BREAKING CHANGES notes, which the preset writes without a commit link
  hash?: string;
  url?: string;
};

export type ChangelogSection = {
  title: string;
  entries: ChangelogEntry[];
};

export type ChangelogRelease = {
  version: string;
  date: string;
  compareUrl?: string;
  sections: ChangelogSection[];
};

// `## [0.5.10](compareUrl) (2025-09-26)`, or the same heading without the compare link
const releaseHeadingRegex = /^#{1,4}\s+(?:\[([^\]]+)\]\(([^)]+)\)|([^\s([]+))\s+\((\d{4}-\d{2}-\d{2})\)\s*$/;
// `### Bug Fixes`, only reached once the release heading above has been ruled out
const sectionHeadingRegex = /^#{2,4}\s+(\S.*?)\s*$/;
// the preset writes top-level bullets with `*`; a `-` line is a sub-list inside the bullet above it
const bulletRegex = /^\*\s+(.*)$/;
const subListRegex = /^-\s+\S/;
const scopeRegex = /^\*\*(.+?):\*\*\s*/;
// the commit link is identified by its /commit/ url, since it is not always the last link on the line
const commitLinkRegex = /\s*\(\[([0-9a-f]{7,40})\]\(([^)]*\/commit\/[^)]*)\)\)/;
const inlineLinkRegex = /\[([^\]]*)\]\(([^)]+)\)/g;

// turns `abandon publications ([#829](url))` into plain text plus a linked `#829`
const parseInlineLinks = (text: string): ChangelogTextSegment[] => {
  const segments: ChangelogTextSegment[] = [];
  let lastIndex = 0;

  for (const match of text.matchAll(inlineLinkRegex)) {
    const [linkMarkdown, label, url] = match;
    const before = text.slice(lastIndex, match.index);
    if (before) segments.push({ text: before });
    segments.push({ text: label, url });
    lastIndex = match.index + linkMarkdown.length;
  }

  const rest = text.slice(lastIndex);
  if (rest) segments.push({ text: rest });

  return segments;
};

const parseBullet = (body: string): ChangelogEntry => {
  let rest = body;

  const scopeMatch = rest.match(scopeRegex);
  const scope = scopeMatch?.[1];
  if (scopeMatch) rest = rest.slice(scopeMatch[0].length);

  const commitMatch = rest.match(commitLinkRegex);
  if (commitMatch) rest = rest.replace(commitLinkRegex, '');

  return {
    scope,
    description: parseInlineLinks(rest.trim()),
    hash: commitMatch?.[1],
    url: commitMatch?.[2],
  };
};

export const parseChangelog = (markdown: string): ChangelogRelease[] => {
  const releases: ChangelogRelease[] = [];
  let release: ChangelogRelease | undefined;
  let section: ChangelogSection | undefined;
  let entry: ChangelogEntry | undefined;
  let sawBlankLine = false;

  for (const line of markdown.split('\n')) {
    const releaseHeading = line.match(releaseHeadingRegex);
    if (releaseHeading) {
      const [, linkedVersion, compareUrl, plainVersion, date] = releaseHeading;
      release = { version: linkedVersion ?? plainVersion, date, compareUrl, sections: [] };
      releases.push(release);
      section = undefined;
      entry = undefined;
      continue;
    }

    const sectionHeading = line.match(sectionHeadingRegex);
    if (sectionHeading) {
      // a section heading before any release heading has nothing to attach to
      if (!release) continue;
      section = { title: sectionHeading[1], entries: [] };
      release.sections.push(section);
      entry = undefined;
      continue;
    }

    const bullet = line.match(bulletRegex);
    if (bullet) {
      if (!release) continue;
      if (!section) {
        // a release that lists entries without a type heading still gets to show them
        section = { title: '', entries: [] };
        release.sections.push(section);
      }
      entry = parseBullet(bullet[1]);
      section.entries.push(entry);
      sawBlankLine = false;
      continue;
    }

    const continuation = line.trim();
    if (!continuation) {
      sawBlankLine = true;
      continue;
    }
    // a BREAKING CHANGES note wraps onto the lines below it, keeping its paragraphs and sub-lists
    if (!entry) continue;
    const separator = subListRegex.test(continuation) ? '\n' : sawBlankLine ? '\n\n' : ' ';
    sawBlankLine = false;
    entry.description = [...entry.description, ...parseInlineLinks(`${separator}${continuation}`)];
  }

  // the preset can emit a heading whose body holds nothing this parser recognises
  for (const parsedRelease of releases) {
    parsedRelease.sections = parsedRelease.sections.filter((parsedSection) => parsedSection.entries.length > 0);
  }

  return releases;
};

// versions contain dots, which are class selectors in querySelector, so anchors use dashes
export const getReleaseAnchorId = (version: string): string => `v${version.replace(/\./g, '-')}`;
